import 'package:birifin_app/data/models/timeline_section.dart';

final List<TimelineSection> mockTimelineSections = [
  TimelineSection(
    id: '1',
    title: 'Introduction',
    timestamp: '0:15',
    content: 'A concise, AI-generated summary of the news article\'s introduction, providing the core context and setting the stage for the key points.',
  ),
  TimelineSection(
    id: '2',
    title: 'Key Points',
    timestamp: '0:45',
    content: 'This section contains a 2-5 line summary of the key points from the news article, generated by AI to be concise and informative. It covers the most critical data and events.',
  ),
  TimelineSection(
    id: '3',
    title: 'Market Reaction',
    timestamp: '1:20',
    content: 'An AI-powered analysis of the market\'s response to the news, including stock movements, investor sentiment, and expert opinions.',
  ),
  TimelineSection(
    id: '4',
    title: 'Expert Analysis',
    timestamp: '2:00',
    content: 'Industry experts weigh in on the implications of these developments and what they mean for the future.',
  ),
  TimelineSection(
    id: '5',
    title: 'Conclusion',
    timestamp: '2:30',
    content: 'A brief recap of the main points and potential future developments to watch for.',
  ),
];
